import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# ============================================================
# Configuration
# ============================================================

# CSV file generated by the controller.
csv_file = "impedance_experiment_log.csv"

# Folder where the generated figures will be saved.
output_folder = Path("evaluation_plots_annotated")
output_folder.mkdir(exist_ok=True)

# Fraction of the experiment used as steady-state interval.
steady_state_fraction = 0.2


# ============================================================
# Load CSV log file
# ============================================================

data = pd.read_csv(csv_file)


# ============================================================
# Compute error norms
# ============================================================

data["e_p_norm"] = np.sqrt(
    data["e_p_x"]**2 +
    data["e_p_y"]**2 +
    data["e_p_z"]**2
)

data["e_R_norm"] = np.sqrt(
    data["e_R_x"]**2 +
    data["e_R_y"]**2 +
    data["e_R_z"]**2
)


# ============================================================
# Helper functions
# ============================================================

def steady_state_info(time, signal, fraction=0.2):
    """
    Return steady-state interval start index, start time, and mean value
    over the final fraction of the signal.
    """
    start_index = int((1.0 - fraction) * len(signal))
    start_time = time.iloc[start_index]
    mean_value = np.mean(signal.iloc[start_index:])
    return start_index, start_time, mean_value


def max_info(time, signal):
    """
    Return the time, value, and index of the maximum value of a signal.
    """
    idx = int(np.argmax(signal.to_numpy()))
    return time.iloc[idx], signal.iloc[idx], idx


def abs_max_info(time, signal):
    """
    Return the time, value, and index of the maximum absolute value
    of a signal.
    """
    idx = int(np.argmax(np.abs(signal.to_numpy())))
    return time.iloc[idx], signal.iloc[idx], idx


def compute_overshoot_info(time, error_component):
    """
    Compute overshoot after the first zero crossing of one error component.
    Returns:
        - overshoot magnitude
        - time of overshoot
        - overshoot value at that time
        - zero-crossing time
        - index of overshoot
    If the component does not cross zero, overshoot is set to zero.
    """
    signal = np.asarray(error_component)
    t = np.asarray(time)

    zero_crossings = np.where(np.diff(np.sign(signal)) != 0)[0]

    if len(zero_crossings) == 0:
        return 0.0, None, None, None, None

    first_crossing_index = zero_crossings[0]
    first_crossing_time = t[first_crossing_index]

    tail = signal[first_crossing_index:]
    tail_abs = np.abs(tail)
    local_idx = int(np.argmax(tail_abs))
    overshoot_index = first_crossing_index + local_idx
    overshoot_value = signal[overshoot_index]
    overshoot_time = t[overshoot_index]
    overshoot_magnitude = abs(overshoot_value)

    return overshoot_magnitude, overshoot_time, overshoot_value, first_crossing_time, overshoot_index


def add_max_annotation(ax, x, y, text_prefix, y_offset_factor=0.06):
    """
    Add an annotation for a maximum value.
    """
    y_range = ax.get_ylim()[1] - ax.get_ylim()[0]
    ax.plot(x, y, marker="o")
    ax.annotate(
        f"{text_prefix}\n({x:.2f} s, {y:.4f})",
        xy=(x, y),
        xytext=(x, y + y_offset_factor * y_range),
        arrowprops=dict(arrowstyle="->"),
    )


def add_steady_state_annotation(ax, start_time, end_time, mean_value, label_text, y_offset_factor=0.08):
    """
    Shade the steady-state interval and add a mean-value annotation.
    """
    ax.axvspan(start_time, end_time, alpha=0.15)
    ax.axhline(mean_value, linestyle="--")
    y_range = ax.get_ylim()[1] - ax.get_ylim()[0]
    ax.annotate(
        f"{label_text} = {mean_value:.4f}",
        xy=(end_time, mean_value),
        xytext=(start_time, mean_value + y_offset_factor * y_range),
        arrowprops=dict(arrowstyle="->"),
    )


def add_overshoot_annotation(ax, time, signal, component_name):
    """
    Mark and annotate overshoot on one error component, if it exists.
    """
    overshoot_mag, overshoot_time, overshoot_value, crossing_time, _ = compute_overshoot_info(time, signal)

    if overshoot_time is not None:
        ax.axvline(crossing_time, linestyle=":")
        ax.plot(overshoot_time, overshoot_value, marker="o")
        y_range = ax.get_ylim()[1] - ax.get_ylim()[0]
        ax.annotate(
            f"{component_name} overshoot = {overshoot_mag:.4f}",
            xy=(overshoot_time, overshoot_value),
            xytext=(overshoot_time, overshoot_value + 0.08 * y_range),
            arrowprops=dict(arrowstyle="->"),
        )

    return overshoot_mag


# ============================================================
# Numerical evaluation
# ============================================================

t_ep_max, e_p_max, _ = max_info(data["time"], data["e_p_norm"])
t_eR_max, e_R_max, _ = max_info(data["time"], data["e_R_norm"])

ss_idx_ep, ss_start_ep, e_p_ss = steady_state_info(data["time"], data["e_p_norm"], steady_state_fraction)
ss_idx_eR, ss_start_eR, e_R_ss = steady_state_info(data["time"], data["e_R_norm"], steady_state_fraction)

overshoot_ep_x = compute_overshoot_info(data["time"], data["e_p_x"])[0]
overshoot_ep_y = compute_overshoot_info(data["time"], data["e_p_y"])[0]
overshoot_ep_z = compute_overshoot_info(data["time"], data["e_p_z"])[0]

overshoot_eR_x = compute_overshoot_info(data["time"], data["e_R_x"])[0]
overshoot_eR_y = compute_overshoot_info(data["time"], data["e_R_y"])[0]
overshoot_eR_z = compute_overshoot_info(data["time"], data["e_R_z"])[0]

delta_p_max = e_p_max

tau_max = {}
tau_max_info = {}
for i in range(1, 8):
    column = f"tau_{i}"
    if column in data.columns:
        time_i, value_i, idx_i = abs_max_info(data["time"], data[column])
        tau_max[column] = abs(value_i)
        tau_max_info[column] = (time_i, value_i, idx_i)


# ============================================================
# Print evaluation results
# ============================================================

print("Evaluation Results")
print("------------------")
print(f"Maximum positional error:       {e_p_max:.6f} m at t = {t_ep_max:.3f} s")
print(f"Steady-state positional error:  {e_p_ss:.6f} m")
print()
print(f"Maximum rotational error:       {e_R_max:.6f} rad at t = {t_eR_max:.3f} s")
print(f"Steady-state rotational error:  {e_R_ss:.6f} rad")
print()
print("Position overshoot:")
print(f"  e_p_x overshoot: {overshoot_ep_x:.6f} m")
print(f"  e_p_y overshoot: {overshoot_ep_y:.6f} m")
print(f"  e_p_z overshoot: {overshoot_ep_z:.6f} m")
print()
print("Rotational overshoot:")
print(f"  e_R_x overshoot: {overshoot_eR_x:.6f} rad")
print(f"  e_R_y overshoot: {overshoot_eR_y:.6f} rad")
print(f"  e_R_z overshoot: {overshoot_eR_z:.6f} rad")
print()
print(f"Maximum compliance displacement: {delta_p_max:.6f} m")
print()
print("Maximum commanded joint torques:")
for key, value in tau_max.items():
    print(f"  {key}: {value:.6f} Nm")


# ============================================================
# Plot 1: desired and measured position
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["p_d_x"], label=r"$p_{d,x}$")
plt.plot(data["time"], data["p_EE_x"], "--", label=r"$p_{\mathrm{EE},x}$")
plt.plot(data["time"], data["p_d_y"], label=r"$p_{d,y}$")
plt.plot(data["time"], data["p_EE_y"], "--", label=r"$p_{\mathrm{EE},y}$")
plt.plot(data["time"], data["p_d_z"], label=r"$p_{d,z}$")
plt.plot(data["time"], data["p_EE_z"], "--", label=r"$p_{\mathrm{EE},z}$")
plt.xlabel("Time [s]")
plt.ylabel("Position [m]")
plt.title("Desired and Measured End-Effector Position")
plt.legend(ncol=2)
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "desired_measured_position.png", dpi=200)
plt.show()


# ============================================================
# Plot 2: position error components with overshoot
# ============================================================

fig, ax = plt.subplots(figsize=(8, 4.5))
ax.plot(data["time"], data["e_p_x"], label=r"$e_{p,x}$")
ax.plot(data["time"], data["e_p_y"], label=r"$e_{p,y}$")
ax.plot(data["time"], data["e_p_z"], label=r"$e_{p,z}$")
ax.set_xlabel("Time [s]")
ax.set_ylabel("Position error [m]")
ax.set_title("Position Error Components")
ax.grid(True)

# Add overshoot annotations
add_overshoot_annotation(ax, data["time"], data["e_p_x"], r"$e_{p,x}$")
add_overshoot_annotation(ax, data["time"], data["e_p_y"], r"$e_{p,y}$")
add_overshoot_annotation(ax, data["time"], data["e_p_z"], r"$e_{p,z}$")

ax.legend()
fig.tight_layout()
fig.savefig(output_folder / "position_error_components_annotated.png", dpi=200)
plt.show()


# ============================================================
# Plot 3: position error norm with maximum and steady-state
# ============================================================

fig, ax = plt.subplots(figsize=(8, 4.5))
ax.plot(data["time"], data["e_p_norm"], label=r"$\|e_p\|$")
ax.set_xlabel("Time [s]")
ax.set_ylabel("Position error norm [m]")
ax.set_title("Position Error Norm")
ax.grid(True)

add_max_annotation(ax, t_ep_max, e_p_max, r"$e_{p,\max}$")
add_steady_state_annotation(
    ax,
    ss_start_ep,
    data["time"].iloc[-1],
    e_p_ss,
    r"$e_{p,\mathrm{ss}}$"
)

ax.legend()
fig.tight_layout()
fig.savefig(output_folder / "position_error_norm_annotated.png", dpi=200)
plt.show()


# ============================================================
# Plot 4: rotational error components with overshoot
# ============================================================

fig, ax = plt.subplots(figsize=(8, 4.5))
ax.plot(data["time"], data["e_R_x"], label=r"$e_{R,x}$")
ax.plot(data["time"], data["e_R_y"], label=r"$e_{R,y}$")
ax.plot(data["time"], data["e_R_z"], label=r"$e_{R,z}$")
ax.set_xlabel("Time [s]")
ax.set_ylabel("Rotational error [rad]")
ax.set_title("Rotational Error Components")
ax.grid(True)

add_overshoot_annotation(ax, data["time"], data["e_R_x"], r"$e_{R,x}$")
add_overshoot_annotation(ax, data["time"], data["e_R_y"], r"$e_{R,y}$")
add_overshoot_annotation(ax, data["time"], data["e_R_z"], r"$e_{R,z}$")

ax.legend()
fig.tight_layout()
fig.savefig(output_folder / "rotational_error_components_annotated.png", dpi=200)
plt.show()


# ============================================================
# Plot 5: rotational error norm with maximum and steady-state
# ============================================================

fig, ax = plt.subplots(figsize=(8, 4.5))
ax.plot(data["time"], data["e_R_norm"], label=r"$\|e_R\|$")
ax.set_xlabel("Time [s]")
ax.set_ylabel("Rotational error norm [rad]")
ax.set_title("Rotational Error Norm")
ax.grid(True)

add_max_annotation(ax, t_eR_max, e_R_max, r"$e_{R,\max}$")
add_steady_state_annotation(
    ax,
    ss_start_eR,
    data["time"].iloc[-1],
    e_R_ss,
    r"$e_{R,\mathrm{ss}}$"
)

ax.legend()
fig.tight_layout()
fig.savefig(output_folder / "rotational_error_norm_annotated.png", dpi=200)
plt.show()


# ============================================================
# Plot 6: Cartesian impedance forces
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["f_x"], label=r"$f_x$")
plt.plot(data["time"], data["f_y"], label=r"$f_y$")
plt.plot(data["time"], data["f_z"], label=r"$f_z$")
plt.xlabel("Time [s]")
plt.ylabel("Force [N]")
plt.title("Cartesian Impedance Forces")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "cartesian_forces.png", dpi=200)
plt.show()


# ============================================================
# Plot 7: Cartesian impedance moments
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["m_x"], label=r"$m_x$")
plt.plot(data["time"], data["m_y"], label=r"$m_y$")
plt.plot(data["time"], data["m_z"], label=r"$m_z$")
plt.xlabel("Time [s]")
plt.ylabel("Moment [Nm]")
plt.title("Cartesian Impedance Moments")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "cartesian_moments.png", dpi=200)
plt.show()


# ============================================================
# Plot 8: commanded joint torques with maxima
# ============================================================

fig, ax = plt.subplots(figsize=(8, 4.5))
for i in range(1, 8):
    column = f"tau_{i}"
    if column in data.columns:
        ax.plot(data["time"], data[column], label=rf"$\tau_{i}$")

for column, (time_i, value_i, idx_i) in tau_max_info.items():
    ax.plot(time_i, value_i, marker="o")
    y_range = ax.get_ylim()[1] - ax.get_ylim()[0]
    ax.annotate(
        f"{column.replace('_', r'\_')} max = {abs(value_i):.3f}",
        xy=(time_i, value_i),
        xytext=(time_i, value_i + 0.06 * y_range),
        arrowprops=dict(arrowstyle="->"),
    )

ax.set_xlabel("Time [s]")
ax.set_ylabel("Joint torque [Nm]")
ax.set_title("Commanded Joint Torques")
ax.legend(ncol=2)
ax.grid(True)
fig.tight_layout()
fig.savefig(output_folder / "commanded_joint_torques_annotated.png", dpi=200)
plt.show()


# ============================================================
# Plot 9: compliance displacement with maximum and steady-state
# ============================================================

fig, ax = plt.subplots(figsize=(8, 4.5))
ax.plot(data["time"], data["e_p_norm"], label=r"$\Delta p(t)=\|e_p(t)\|$")
ax.set_xlabel("Time [s]")
ax.set_ylabel("Displacement from desired pose [m]")
ax.set_title("Compliance Evaluation: End-Effector Displacement")
ax.grid(True)

add_max_annotation(ax, t_ep_max, delta_p_max, r"$\Delta p_{\max}$")
add_steady_state_annotation(
    ax,
    ss_start_ep,
    data["time"].iloc[-1],
    e_p_ss,
    r"steady-state displacement"
)

ax.legend()
fig.tight_layout()
fig.savefig(output_folder / "compliance_displacement_annotated.png", dpi=200)
plt.show()


print()
print(f"Annotated figures saved in folder: {output_folder.resolve()}")
