import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


# ============================================================
# Configuration
# ============================================================

# Name of the CSV file generated by the controller.
# Place this Python file in the same folder as the CSV file,
# or replace the path below with the full path to your CSV file.
csv_file = "impedance_experiment_log.csv"

# Folder where the generated figures will be saved.
output_folder = Path("evaluation_plots")
output_folder.mkdir(exist_ok=True)


# ============================================================
# Load CSV log file
# ============================================================

data = pd.read_csv(csv_file)


# ============================================================
# Compute error norms
# ============================================================

data["e_p_norm"] = np.sqrt(
    data["e_p_x"]**2 +
    data["e_p_y"]**2 +
    data["e_p_z"]**2
)

data["e_R_norm"] = np.sqrt(
    data["e_R_x"]**2 +
    data["e_R_y"]**2 +
    data["e_R_z"]**2
)


# ============================================================
# Evaluation functions
# ============================================================

def steady_state_error(error_norm, percentage=0.2):
    """
    Compute the mean error over the final part of the experiment.
    By default, the final 20% of the experiment is used.
    """
    start_index = int((1.0 - percentage) * len(error_norm))
    return np.mean(error_norm[start_index:])


def maximum_error(error_norm):
    """
    Compute the maximum value of an error norm.
    """
    return np.max(error_norm)


def compute_overshoot(error_component):
    """
    Compute overshoot after the first zero crossing of one error component.
    If the component does not cross zero, the overshoot is set to zero.
    """
    error_component = np.asarray(error_component)

    zero_crossings = np.where(np.diff(np.sign(error_component)) != 0)[0]

    if len(zero_crossings) == 0:
        return 0.0

    first_crossing = zero_crossings[0]
    return np.max(np.abs(error_component[first_crossing:]))


# ============================================================
# Numerical evaluation
# ============================================================

e_p_max = maximum_error(data["e_p_norm"])
e_R_max = maximum_error(data["e_R_norm"])

e_p_ss = steady_state_error(data["e_p_norm"])
e_R_ss = steady_state_error(data["e_R_norm"])

overshoot_ep_x = compute_overshoot(data["e_p_x"])
overshoot_ep_y = compute_overshoot(data["e_p_y"])
overshoot_ep_z = compute_overshoot(data["e_p_z"])

overshoot_eR_x = compute_overshoot(data["e_R_x"])
overshoot_eR_y = compute_overshoot(data["e_R_y"])
overshoot_eR_z = compute_overshoot(data["e_R_z"])

tau_max = {}
for i in range(1, 8):
    column = f"tau_{i}"
    if column in data.columns:
        tau_max[column] = data[column].abs().max()


# ============================================================
# Print evaluation results
# ============================================================

print("Evaluation Results")
print("------------------")
print(f"Maximum positional error:      {e_p_max:.6f} m")
print(f"Steady-state positional error: {e_p_ss:.6f} m")
print()
print(f"Maximum rotational error:      {e_R_max:.6f} rad")
print(f"Steady-state rotational error: {e_R_ss:.6f} rad")
print()
print("Position overshoot:")
print(f"  e_p_x overshoot: {overshoot_ep_x:.6f} m")
print(f"  e_p_y overshoot: {overshoot_ep_y:.6f} m")
print(f"  e_p_z overshoot: {overshoot_ep_z:.6f} m")
print()
print("Rotational overshoot:")
print(f"  e_R_x overshoot: {overshoot_eR_x:.6f} rad")
print(f"  e_R_y overshoot: {overshoot_eR_y:.6f} rad")
print(f"  e_R_z overshoot: {overshoot_eR_z:.6f} rad")
print()
print("Maximum commanded joint torques:")
for key, value in tau_max.items():
    print(f"  {key}: {value:.6f} Nm")


# ============================================================
# Plot 1: measured and desired position
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["p_d_x"], label=r"$p_{d,x}$")
plt.plot(data["time"], data["p_EE_x"], "--", label=r"$p_{\mathrm{EE},x}$")
plt.plot(data["time"], data["p_d_y"], label=r"$p_{d,y}$")
plt.plot(data["time"], data["p_EE_y"], "--", label=r"$p_{\mathrm{EE},y}$")
plt.plot(data["time"], data["p_d_z"], label=r"$p_{d,z}$")
plt.plot(data["time"], data["p_EE_z"], "--", label=r"$p_{\mathrm{EE},z}$")
plt.xlabel("Time [s]")
plt.ylabel("Position [m]")
plt.title("Desired and Measured End-Effector Position")
plt.legend(ncol=2)
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "desired_measured_position.png", dpi=200)
plt.show()


# ============================================================
# Plot 2: position error components
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["e_p_x"], label=r"$e_{p,x}$")
plt.plot(data["time"], data["e_p_y"], label=r"$e_{p,y}$")
plt.plot(data["time"], data["e_p_z"], label=r"$e_{p,z}$")
plt.xlabel("Time [s]")
plt.ylabel("Position error [m]")
plt.title("Position Error Components")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "position_error_components.png", dpi=200)
plt.show()


# ============================================================
# Plot 3: position error norm
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["e_p_norm"], label=r"$\|e_p\|$")
plt.xlabel("Time [s]")
plt.ylabel("Position error norm [m]")
plt.title("Position Error Norm")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "position_error_norm.png", dpi=200)
plt.show()


# ============================================================
# Plot 4: rotational error components
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["e_R_x"], label=r"$e_{R,x}$")
plt.plot(data["time"], data["e_R_y"], label=r"$e_{R,y}$")
plt.plot(data["time"], data["e_R_z"], label=r"$e_{R,z}$")
plt.xlabel("Time [s]")
plt.ylabel("Rotational error [rad]")
plt.title("Rotational Error Components")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "rotational_error_components.png", dpi=200)
plt.show()


# ============================================================
# Plot 5: rotational error norm
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["e_R_norm"], label=r"$\|e_R\|$")
plt.xlabel("Time [s]")
plt.ylabel("Rotational error norm [rad]")
plt.title("Rotational Error Norm")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "rotational_error_norm.png", dpi=200)
plt.show()


# ============================================================
# Plot 6: Cartesian impedance forces
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["f_x"], label=r"$f_x$")
plt.plot(data["time"], data["f_y"], label=r"$f_y$")
plt.plot(data["time"], data["f_z"], label=r"$f_z$")
plt.xlabel("Time [s]")
plt.ylabel("Force [N]")
plt.title("Cartesian Impedance Forces")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "cartesian_forces.png", dpi=200)
plt.show()


# ============================================================
# Plot 7: Cartesian impedance moments
# ============================================================

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["m_x"], label=r"$m_x$")
plt.plot(data["time"], data["m_y"], label=r"$m_y$")
plt.plot(data["time"], data["m_z"], label=r"$m_z$")
plt.xlabel("Time [s]")
plt.ylabel("Moment [Nm]")
plt.title("Cartesian Impedance Moments")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "cartesian_moments.png", dpi=200)
plt.show()


# ============================================================
# Plot 8: commanded joint torques
# ============================================================

plt.figure(figsize=(8, 4.5))
for i in range(1, 8):
    column = f"tau_{i}"
    if column in data.columns:
        plt.plot(data["time"], data[column], label=rf"$\tau_{i}$")

plt.xlabel("Time [s]")
plt.ylabel("Joint torque [Nm]")
plt.title("Commanded Joint Torques")
plt.legend(ncol=2)
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "commanded_joint_torques.png", dpi=200)
plt.show()


# ============================================================
# Plot 9: compliance displacement
# ============================================================
# This plot is useful for compliance experiments.
# The maximum value of ||e_p|| corresponds to the maximum displacement
# from the desired pose during manual interaction.

plt.figure(figsize=(8, 4.5))
plt.plot(data["time"], data["e_p_norm"], label=r"$\Delta p(t)=\|e_p(t)\|$")
plt.xlabel("Time [s]")
plt.ylabel("Displacement from desired pose [m]")
plt.title("Compliance Evaluation: End-Effector Displacement")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig(output_folder / "compliance_displacement.png", dpi=200)
plt.show()


print()
print(f"Figures saved in folder: {output_folder.resolve()}")
